#+STARTUP: content
#+STARTUP: overview
#+STARTUP: indent
#+TITLE: Análise do Tamanho do Volume


* Experimentos

Foram realizados experimentos para determinar qual tamanho de volume tem a
máxima ocupação dos trabalhadores no /star-fletcher/.
Utilizou-se 3 máquinas, a /draco/, /poti/ e /cei/ para os experimentos, sendo
gerados a partir do arquivo /experiments.R/.

% use C-c ' para ver os conteúdos do arquivo
% Bonus: use C-c - para fazer um texto virar lista
#+INCLUDE: "./experiments.R" src R

Nisso, tenho agora que descobrir qual o menor tamanho de meio que ocupa todos os trabalhadores.

** Conversão
Convertemos os /prof_file_/ para /.parquet/

Organizar os arquivos
#+BEGIN_SRC shell 
  DIR='./experimental-results'

  pushd $DIR

  for d in "poti2" "draco1" "cei2"; do
    echo $d
    pushd ./$d
    for file in prof_file_*; do
        temp=${file#prof_file_}
        temp=${temp%_0}

        IFS='-' read -r io size seg iter <<< "$temp"
        FOLDER=./$io/$size/$seg/$iter
        mkdir -p $FOLDER
        mv $file $FOLDER
    done
    popd
  done


#+END_SRC

#+RESULTS:
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results        | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size                      |                                                              |
| poti2                                                                                    |                                                                                   |                                                              |
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results/poti2  | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size |
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results        | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size                      |                                                              |
| draco1                                                                                   |                                                                                   |                                                              |
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results/draco1 | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size |
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results        | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size                      |                                                              |
| cei2                                                                                     |                                                                                   |                                                              |
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results/cei2   | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size |
| ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size/experimental-results        | ~/experiments/msamples-cpu-star-fletcher/full-ocupation-size                      |                                                              |

O comando ~dir="${file%/*}"~, pega o conteúdo de file, remove do fim (símbolo %) a última ocorrência de / seguido de qualquer coisa.
Se usa-se #, seria a primeira ocorrência.

#+BEGIN_SRC shell 
  find ./experimental-results -type f -name "prof_file_*_0" -exec bash -c '
    file="$1"
    dir="${file%/*}"
    echo "Processing directory: $dir"
    cd "$dir" && starvz -1 .
' _ {} \;
#+END_SRC

#+RESULTS:


** Análise

#+BEGIN_SRC R :session *R* :async yes
  options(crayon.enabled = FALSE)
  library(starvz)
  library(tidyverse)
  library(ggplot2)

  base_dir = "./experimental-results"
  dirs = list.dirs(base_dir, recursive = FALSE)

  ds <- tibble(DIR = dirs) |>
    mutate(Machine = basename(DIR))

  experiments <- read_csv('./experiments-cpu.csv')

  all <- ds |> cross_join(experiments)

  data_table <- all |>
     mutate(PATH = paste0(DIR,"/", WithIO, "/", Size, "/",Segmentation, "/", Steps)) |>
    #filter(Size < 176) |>
     mutate(DATA = map(PATH, starvz_read)) |>
     mutate(OCCUPANCY = map(DATA, function(x) {
       app = x$Application
       app |>
         group_by(ResourceId) |>
         summarize(
           TD = sum(Duration),
           MakeSpan = max(End) - min(Start),
           .groups = "drop"
           ) |>
         summarize(P = sum(TD) / sum(MakeSpan) * 100)
     })) |> 
     unnest(OCCUPANCY)
#+END_SRC


#+BEGIN_SRC R :session *R* :async yes
  plot <- function(io_state){
    ggplot(data_table |> filter(WithIO == io_state), aes(x = Size, y = P, color = as.factor(Steps))) +
    geom_point(size = 3, alpha = 0.8) +
    scale_y_continuous(breaks = seq(0, 100, by = 5)) +
    ylim(0,100) +
    geom_line(aes(group = Steps), linewidth = 1) + # Adds lines connecting the points
    facet_grid(Machine ~ Segmentation, labeller = label_both) + # Creates a separate panel for each Segmentation size
    #scale_color_manual(values = c("0" = "#F8766D", "1" = "#00BFC4"), 
    #                   labels = c("0 (No IO)", "1 (With IO)")) +
    labs(
        title = paste0("Occupancy vs. Size when WithIO = ", io_state),
        subtitle = "Faceted by Segmentation Size",
        x = "Size",
        y = "Occupancy (%)",
        color = "I/O Status"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")
  }
  plot(0) + plot(1)

#+END_SRC

#+RESULTS:

Gráfico estranho, validando que não há tasks de /block_write/ quando /WithIO == 0/.

#+BEGIN_SRC R :session *R* :async yes
        data_table |>
          filter(WithIO == 0) |>
          mutate(BW = map(DATA, function(x){
            app = x$Application
            app |> group_by(Value) |> summarize(N = n())
          })) |>
          unnest(BW) |>
          select(Machine, Size, Value, N) |>
          filter(Value != "wave_insertion") |>
          filter(Value != "wave_propagation") 

#+END_SRC

#+RESULTS:

Realmente não tem. Não sei explicar o fenômeno.

Vamos fixar nos tamanhos 96, 136 e 176 e verificar qual tem o maior Msamples para IO=0.

#+BEGIN_SRC R :session *R* :async yes :results output silent
  library(readr)
  library(stringr)
  extra_data = "./other-files-results/"

  msamples_table <- all |>
    filter(Blocks == 0.1) |>
    mutate(DIR = sub("./", extra_data, DIR, fixed = TRUE)) |>
    mutate(FILE = paste0(DIR,"/stdout-", WithIO, "-", Size, "-",Segmentation, "-", Steps, ".out")) |>
    mutate(Msamples = map_dbl(FILE, function(file) {
      #print(file)
      read_lines(file) |>
        tail(1) |>
        str_remove("Msamples/s: ") |>
        as.numeric()
    })) |>
    arrange(-Msamples) |>
    select(-DIR, -FILE, -Blocks)
#+END_SRC


#+BEGIN_SRC R :session *R* :async yes  :results output silent
  plot_msamples <- function(io_state){
    ggplot(msamples_table |> filter(WithIO == io_state), aes(x = Size, y = Msamples, color = as.factor(Steps))) +
    geom_point(size = 3, alpha = 0.8) +
    geom_line(aes(group = Steps), linewidth = 1) + # Adds lines connecting the points
    scale_y_continuous(breaks = seq(0, 100, by = 5)) +
    facet_grid(Machine ~ Segmentation, labeller = label_both) + 
    labs(
        title = paste0("Msamples vs. Size when WithIO = ", io_state),
        subtitle = "Faceted by Segmentation Size",
        x = "Size",
        y = "Msamples/s",
        color = "I/O Status"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")
  }
  plot_msamples(0) + plot_msamples(1)

#+END_SRC

#+RESULTS:



